package memory

import (
	"time"

	"memory-safe-english/services/api/internal/domain"
)

func additionalSeedCatalog(now time.Time) []domain.Content {
	return []domain.Content{
		{
			ID:          "cnt_self_intro_005",
			Title:       "Self Introduction: Lab Role",
			ContentType: "reading",
			Level:       "intro",
			Topic:       "self_intro",
			Language:    "en",
			RawText:     "In my lab, I help with user interviews and short reading experiments.",
			SummaryText: "Simple lab role statement",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_self_intro_006",
			Title:       "Self Introduction: Listening Goal",
			ContentType: "listening",
			Level:       "intro",
			Topic:       "self_intro",
			Language:    "en",
			RawText:     "My main goal this year is to follow short discussions without losing the topic halfway through.",
			SummaryText: "Listening-focused self introduction goal",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_self_intro_007",
			Title:       "Self Introduction: Conference Version",
			ContentType: "speaking_template",
			Level:       "intro",
			Topic:       "self_intro",
			Language:    "en",
			RawText:     "Hello. I am Yui from Tokyo. My topic is reading support for overloaded learners.",
			SummaryText: "Conference-style self introduction in three short units",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_self_intro_008",
			Title:       "Self Introduction: Preferred Pace",
			ContentType: "reading",
			Level:       "intro",
			Topic:       "self_intro",
			Language:    "en",
			RawText:     "I understand better when we move step by step, so I sometimes ask for the main point first.",
			SummaryText: "Preference statement about slower pacing",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_daily_007",
			Title:       "Daily Reading: Pharmacy Question",
			ContentType: "reading",
			Level:       "intro",
			Topic:       "daily",
			Language:    "en",
			RawText:     "Do I take this medicine before breakfast, or is it better after I eat something?",
			SummaryText: "Short medication timing question",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_daily_008",
			Title:       "Daily Listening: Gate Change",
			ContentType: "listening",
			Level:       "intro",
			Topic:       "daily",
			Language:    "en",
			RawText:     "Attention please. The bus for terminal two will now leave from gate seven instead of gate four.",
			SummaryText: "Transport announcement with one change",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_daily_009",
			Title:       "Daily Speaking: Ask for Help at a Counter",
			ContentType: "speaking_template",
			Level:       "intro",
			Topic:       "daily",
			Language:    "en",
			RawText:     "I need some help. This form is confusing. Could you show me the first part?",
			SummaryText: "Counter help request in short units",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_daily_010",
			Title:       "Daily Reading: Hotel Check-in",
			ContentType: "reading",
			Level:       "intro",
			Topic:       "daily",
			Language:    "en",
			RawText:     "I have a reservation under Sato, and I would like to confirm whether breakfast is included.",
			SummaryText: "Hotel check-in request with one confirmation",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_daily_011",
			Title:       "Daily Listening: Lost Item Desk",
			ContentType: "listening",
			Level:       "intro",
			Topic:       "daily",
			Language:    "en",
			RawText:     "If you lost a black umbrella, please come to the information desk near the main entrance.",
			SummaryText: "Lost item announcement with one action",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_daily_012",
			Title:       "Daily Speaking: Change the Time",
			ContentType: "speaking_template",
			Level:       "intro",
			Topic:       "daily",
			Language:    "en",
			RawText:     "Tomorrow is difficult. Could we move it to the afternoon? Two o'clock is best for me.",
			SummaryText: "Time-change template in short steps",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_research_009",
			Title:       "Research Reading: Participant Profile",
			ContentType: "reading",
			Level:       "intermediate",
			Topic:       "research",
			Language:    "en",
			RawText:     "Most participants were university students who reported frequent difficulty holding long spoken explanations in memory.",
			SummaryText: "Participant description tied to memory load",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_research_010",
			Title:       "Research Listening: Procedure Step",
			ContentType: "listening",
			Level:       "intermediate",
			Topic:       "research",
			Language:    "en",
			RawText:     "First, participants read a short text in chunk mode, and then they explained the main point in their own words.",
			SummaryText: "Procedure sentence with two ordered actions",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_research_011",
			Title:       "Research Speaking: Method in Steps",
			ContentType: "speaking_template",
			Level:       "intermediate",
			Topic:       "research",
			Language:    "en",
			RawText:     "First, we compared two readers. Next, we measured overload. Finally, we checked summary accuracy.",
			SummaryText: "Method explanation in three steps",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_research_012",
			Title:       "Research Reading: Main Contribution",
			ContentType: "reading",
			Level:       "intermediate",
			Topic:       "research",
			Language:    "en",
			RawText:     "Our main contribution is not harder content but a safer presentation style that protects the learner from overload.",
			SummaryText: "Contribution statement with contrast",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_research_013",
			Title:       "Research Listening: Interpretation",
			ContentType: "listening",
			Level:       "intermediate",
			Topic:       "research",
			Language:    "en",
			RawText:     "This suggests that better comprehension can come from reduced holding demand, even when vocabulary knowledge stays the same.",
			SummaryText: "Interpretation sentence with one inference",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_research_014",
			Title:       "Research Speaking: Limitation and Next Step",
			ContentType: "speaking_template",
			Level:       "intermediate",
			Topic:       "research",
			Language:    "en",
			RawText:     "There is one limitation. We used short texts first. The next step is testing longer materials.",
			SummaryText: "Limitation explanation in short units",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_meeting_007",
			Title:       "Meeting Reading: Scope Decision",
			ContentType: "reading",
			Level:       "intermediate",
			Topic:       "meeting",
			Language:    "en",
			RawText:     "For this release, we will keep the onboarding flow simple and postpone the advanced analytics tab.",
			SummaryText: "Scope decision with one postponed feature",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_meeting_008",
			Title:       "Meeting Listening: Owner and Deadline",
			ContentType: "listening",
			Level:       "intermediate",
			Topic:       "meeting",
			Language:    "en",
			RawText:     "Aya will update the prototype tonight, and Jun will review the wording before noon tomorrow.",
			SummaryText: "Owner and deadline listening practice",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_meeting_009",
			Title:       "Meeting Speaking: Simple Status Update",
			ContentType: "speaking_template",
			Level:       "intermediate",
			Topic:       "meeting",
			Language:    "en",
			RawText:     "The build is stable. Login works now. The remaining issue is the settings screen.",
			SummaryText: "Simple project status update",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_meeting_010",
			Title:       "Meeting Reading: Ask for Clarification",
			ContentType: "reading",
			Level:       "intermediate",
			Topic:       "meeting",
			Language:    "en",
			RawText:     "Before we continue, can we confirm whether the deadline changed for the whole team or only for the design task?",
			SummaryText: "Clarification question with two options",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_rescue_007",
			Title:       "Rescue: Ask for the Keyword",
			ContentType: "rescue",
			Level:       "intro",
			Topic:       "rescue",
			Language:    "en",
			RawText:     "Can you give me the key word first?",
			SummaryText: "Rescue phrase to anchor one key term",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_rescue_008",
			Title:       "Rescue: Ask for One Sentence",
			ContentType: "rescue",
			Level:       "intro",
			Topic:       "rescue",
			Language:    "en",
			RawText:     "Could you say it in one short sentence?",
			SummaryText: "Rescue phrase to reduce sentence length sharply",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_rescue_009",
			Title:       "Rescue: Pause Before Answering",
			ContentType: "rescue",
			Level:       "intro",
			Topic:       "rescue",
			Language:    "en",
			RawText:     "Please wait a moment. I want to answer carefully.",
			SummaryText: "Rescue phrase to create thinking time",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_rescue_010",
			Title:       "Rescue: Ask for Step-by-Step",
			ContentType: "rescue",
			Level:       "intro",
			Topic:       "rescue",
			Language:    "en",
			RawText:     "Could you explain it step by step?",
			SummaryText: "Rescue phrase for multi-step instructions",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
	}
}
