INSERT INTO contents (
    id,
    title,
    content_type,
    level,
    topic,
    language,
    raw_text,
    summary_text
)
VALUES
    ('cnt_self_intro_005', 'Self Introduction: Lab Role', 'reading', 'intro', 'self_intro', 'en', 'In my lab, I help with user interviews and short reading experiments.', 'Simple lab role statement'),
    ('cnt_self_intro_006', 'Self Introduction: Listening Goal', 'listening', 'intro', 'self_intro', 'en', 'My main goal this year is to follow short discussions without losing the topic halfway through.', 'Listening-focused self introduction goal'),
    ('cnt_self_intro_007', 'Self Introduction: Conference Version', 'speaking_template', 'intro', 'self_intro', 'en', 'Hello. I am Yui from Tokyo. My topic is reading support for overloaded learners.', 'Conference-style self introduction in three short units'),
    ('cnt_self_intro_008', 'Self Introduction: Preferred Pace', 'reading', 'intro', 'self_intro', 'en', 'I understand better when we move step by step, so I sometimes ask for the main point first.', 'Preference statement about slower pacing'),
    ('cnt_self_intro_009', 'Self Introduction: Why English Matters', 'reading', 'intro', 'self_intro', 'en', 'English matters for me because I need to explain my research to people outside my department.', 'Why English matters in one clear reason'),
    ('cnt_self_intro_010', 'Self Introduction: Current Challenge', 'reading', 'intro', 'self_intro', 'en', 'My biggest challenge is not vocabulary. It is keeping long explanations in mind while I listen.', 'Challenge statement focused on working memory'),
    ('cnt_self_intro_011', 'Self Introduction: Short Speaking Version', 'speaking_template', 'intro', 'self_intro', 'en', 'I am Rina. I study language learning. My focus is memory-safe communication.', 'Short self introduction with three stable chunks'),
    ('cnt_self_intro_012', 'Self Introduction: Listening Practice', 'listening', 'intro', 'self_intro', 'en', 'Hello, I am Daichi. I work on classroom tools, and I am especially interested in clearer speaking support.', 'Self introduction for short listening practice'),
    ('cnt_daily_013', 'Daily Reading: Return a Book', 'reading', 'intro', 'daily', 'en', 'I borrowed this book last week, but I finished it early and would like to return it today.', 'Library return request with one reason'),
    ('cnt_daily_014', 'Daily Reading: Ask for a Receipt', 'reading', 'intro', 'daily', 'en', 'Could I have a receipt, please? I need it for my travel report.', 'Receipt request with one purpose'),
    ('cnt_daily_015', 'Daily Listening: Platform Change', 'listening', 'intro', 'daily', 'en', 'The local train to Central Station will arrive on platform six instead of platform two.', 'Transport update with one changed platform'),
    ('cnt_daily_016', 'Daily Listening: Store Closing', 'listening', 'intro', 'daily', 'en', 'This store will close in fifteen minutes, so please bring your final items to the front counter.', 'Store closing announcement with one action'),
    ('cnt_daily_017', 'Daily Speaking: Ask for Simpler English', 'speaking_template', 'intro', 'daily', 'en', 'I understand a little. Could you use simpler English? The first point is enough for now.', 'Short speaking template for simpler language'),
    ('cnt_daily_018', 'Daily Speaking: Confirm a Reservation', 'speaking_template', 'intro', 'daily', 'en', 'I have a reservation. My name is Kato. Could you check the time for me?', 'Reservation confirmation in three steps'),
    ('cnt_research_015', 'Research Reading: Data Source', 'reading', 'intermediate', 'research', 'en', 'The dataset included classroom explanations, meeting instructions, and short academic passages with different overload profiles.', 'Data source sentence with three content groups'),
    ('cnt_research_016', 'Research Reading: Evaluation Focus', 'reading', 'intermediate', 'research', 'en', 'We focused on whether learners could keep the main point, not whether they remembered every surface detail.', 'Evaluation focus with explicit contrast'),
    ('cnt_research_017', 'Research Listening: Participant Comment', 'listening', 'intermediate', 'research', 'en', 'Several participants said they felt calmer because they no longer needed to hold the entire sentence at once.', 'Participant feedback for listening practice'),
    ('cnt_research_018', 'Research Listening: Interpretation Step', 'listening', 'intermediate', 'research', 'en', 'This pattern may mean that lower pressure on short-term holding allows more attention for integration.', 'Interpretation sentence with one hypothesis'),
    ('cnt_research_019', 'Research Speaking: Explain the Problem', 'speaking_template', 'intermediate', 'research', 'en', 'The problem is simple. Known words still collapse in long sentences. The burden is in holding and integration.', 'Problem explanation in short research units'),
    ('cnt_research_020', 'Research Speaking: Explain the Result', 'speaking_template', 'intermediate', 'research', 'en', 'The result is clear. Shorter holding demand improved summaries. Confidence also increased.', 'Result explanation in three steps'),
    ('cnt_meeting_011', 'Meeting Reading: Confirm the Goal', 'reading', 'intermediate', 'meeting', 'en', 'Before we discuss the design, can we agree that the main goal for today is a stable demo by Friday?', 'Goal confirmation question for meetings'),
    ('cnt_meeting_012', 'Meeting Reading: Identify the Risk', 'reading', 'intermediate', 'meeting', 'en', 'The main risk is not the feature itself but the time needed to test edge cases before release.', 'Risk statement with contrast'),
    ('cnt_meeting_013', 'Meeting Listening: Review Reminder', 'listening', 'intermediate', 'meeting', 'en', 'Please read the feedback summary tonight and bring one suggested change to tomorrow''s check-in.', 'Review reminder with one deliverable'),
    ('cnt_meeting_014', 'Meeting Listening: Release Condition', 'listening', 'intermediate', 'meeting', 'en', 'We can release this version only if the login issue is resolved and the onboarding text is reviewed.', 'Release condition with two required items'),
    ('cnt_meeting_015', 'Meeting Speaking: Ask for the Main Point', 'speaking_template', 'intermediate', 'meeting', 'en', 'I want to confirm the main point. Is the priority stability first and design second?', 'Meeting clarification in short units'),
    ('cnt_meeting_016', 'Meeting Speaking: State a Blocker', 'speaking_template', 'intermediate', 'meeting', 'en', 'I have one blocker. The login flow is unstable. I need one more day for testing.', 'Blocker report in short speaking steps'),
    ('cnt_rescue_011', 'Rescue: Ask for the Conclusion', 'rescue', 'intro', 'rescue', 'en', 'Could you tell me the conclusion first?', 'Rescue phrase for conclusion-first support'),
    ('cnt_rescue_012', 'Rescue: Ask for a Pause', 'rescue', 'intro', 'rescue', 'en', 'Please pause after each step.', 'Rescue phrase for paced instructions'),
    ('cnt_rescue_013', 'Rescue: Ask What Changed', 'rescue', 'intro', 'rescue', 'en', 'What changed from the last version?', 'Rescue phrase for focused comparison'),
    ('cnt_rescue_014', 'Rescue: Ask to Confirm the Deadline', 'rescue', 'intro', 'rescue', 'en', 'Can we confirm the deadline once more?', 'Rescue phrase for deadline confirmation')
ON CONFLICT (id) DO NOTHING;
