INSERT INTO contents (
    id,
    title,
    content_type,
    level,
    topic,
    language,
    raw_text,
    summary_text
)
VALUES
    ('cnt_self_intro_017', 'Self Introduction: Support Need', 'reading', 'intro', 'self_intro', 'en', 'Sometimes I understand best when I can keep the last sentence visible while I answer.', 'Self introduction about support preference'),
    ('cnt_self_intro_018', 'Self Introduction: Short Strength', 'reading', 'intro', 'self_intro', 'en', 'One of my strengths is explaining ideas in short steps even when the topic is complex.', 'Strength statement in one sentence'),
    ('cnt_self_intro_019', 'Self Introduction: Speaking Goal', 'speaking_template', 'intro', 'self_intro', 'en', 'My speaking goal is simple. I want to stay clear. I want to stay calm.', 'Three-step speaking goal template'),
    ('cnt_self_intro_020', 'Self Introduction: Listening Snapshot', 'listening', 'intro', 'self_intro', 'en', 'I can usually follow short answers, but I lose the thread when the explanation becomes too dense.', 'Short listening profile statement'),
    ('cnt_daily_027', 'Daily Reading: Ask for the Menu Highlight', 'reading', 'intro', 'daily', 'en', 'I do not need the full menu. Could you show me the most popular item first?', 'Menu request focused on one item'),
    ('cnt_daily_028', 'Daily Reading: Ask About Delay', 'reading', 'intro', 'daily', 'en', 'The bus was supposed to arrive at noon, so could you tell me the new time?', 'Delay question with one requested answer'),
    ('cnt_daily_029', 'Daily Listening: Seat Number Change', 'listening', 'intro', 'daily', 'en', 'Your seat has changed to row nine near the window, so please follow the blue sign.', 'Short seat-change announcement'),
    ('cnt_daily_030', 'Daily Listening: Pickup Reminder', 'listening', 'intro', 'daily', 'en', 'Please collect your document at the front desk before five o''clock this evening.', 'Pickup reminder with one deadline'),
    ('cnt_daily_031', 'Daily Speaking: Ask for a Slower Repeat', 'speaking_template', 'intro', 'daily', 'en', 'Could you repeat that more slowly? The first part is enough for me.', 'Short speaking template for slower repetition'),
    ('cnt_daily_032', 'Daily Speaking: Explain a Missed Point', 'speaking_template', 'intro', 'daily', 'en', 'I understood the start, but I missed the last point. Could you repeat that part?', 'Short explanation of a missed point'),
    ('cnt_research_029', 'Research Reading: Background Problem', 'reading', 'intermediate', 'research', 'en', 'Traditional language learning tools often assume that learners can hold long sequences long enough to integrate them.', 'Background problem in one sentence'),
    ('cnt_research_030', 'Research Reading: Interface Choice', 'reading', 'intermediate', 'research', 'en', 'We chose an externalized interface because stable visual anchors can reduce the need for internal holding.', 'Interface choice with one reason'),
    ('cnt_research_031', 'Research Listening: Summary of Method', 'listening', 'intermediate', 'research', 'en', 'The method was straightforward: chunk first, skeleton next, and self-summary after each sentence.', 'Method summary with three phases'),
    ('cnt_research_032', 'Research Listening: Summary of Effect', 'listening', 'intermediate', 'research', 'en', 'The strongest effect appeared when modifier-heavy sentences were shown step by step instead of all at once.', 'Effect summary tied to one condition'),
    ('cnt_research_033', 'Research Speaking: Explain the Comparison', 'speaking_template', 'intermediate', 'research', 'en', 'We compared two displays. One was dense. One protected the main point first.', 'Speaking template for comparison'),
    ('cnt_research_034', 'Research Speaking: Explain Future Work', 'speaking_template', 'intermediate', 'research', 'en', 'The next step is personalization. We want to adjust pauses. We also want to adjust display density.', 'Future-work explanation in short units'),
    ('cnt_meeting_023', 'Meeting Reading: Confirm One Decision', 'reading', 'intermediate', 'meeting', 'en', 'Can we confirm one decision before moving on: is the release still planned for next Friday?', 'Decision confirmation question'),
    ('cnt_meeting_024', 'Meeting Reading: Ask for a Short Update', 'reading', 'intermediate', 'meeting', 'en', 'Before the detailed report, could you give us the short update in one or two sentences?', 'Request for a short update'),
    ('cnt_meeting_025', 'Meeting Listening: Task Split', 'listening', 'intermediate', 'meeting', 'en', 'I will handle the data cleanup, and you can focus on the final review of the slides.', 'Task split in one short sentence'),
    ('cnt_meeting_026', 'Meeting Listening: Main Concern', 'listening', 'intermediate', 'meeting', 'en', 'My main concern is not speed but whether new users can follow the first screen without extra help.', 'Main concern statement for meetings'),
    ('cnt_meeting_027', 'Meeting Speaking: Restate the Goal', 'speaking_template', 'intermediate', 'meeting', 'en', 'Let me restate the goal. We want a stable demo. Fancy features can wait.', 'Goal restatement in short units'),
    ('cnt_meeting_028', 'Meeting Speaking: Ask for Step Order', 'speaking_template', 'intermediate', 'meeting', 'en', 'I am not sure about the order. Which step comes first, review or release?', 'Step-order clarification template'),
    ('cnt_rescue_019', 'Rescue: Ask for the First Answer Only', 'rescue', 'intro', 'rescue', 'en', 'Please give me the first answer only.', 'Rescue phrase for narrowing scope'),
    ('cnt_rescue_020', 'Rescue: Ask for One Sentence at a Time', 'rescue', 'intro', 'rescue', 'en', 'Could you give me one sentence at a time?', 'Rescue phrase for sentence pacing'),
    ('cnt_rescue_021', 'Rescue: Ask for the Action Item', 'rescue', 'intro', 'rescue', 'en', 'What is the action item for me?', 'Rescue phrase for focusing on one task'),
    ('cnt_rescue_022', 'Rescue: Ask for the Key Difference', 'rescue', 'intro', 'rescue', 'en', 'What is the key difference from before?', 'Rescue phrase for comparing versions'),
    ('cnt_rescue_023', 'Rescue: Ask to Hold the Screen', 'rescue', 'intro', 'rescue', 'en', 'Could you keep that sentence on the screen for a moment?', 'Rescue phrase for visual holding support'),
    ('cnt_rescue_024', 'Rescue: Ask to Mark the Core Part', 'rescue', 'intro', 'rescue', 'en', 'Can you mark the core part first?', 'Rescue phrase for core highlighting'),
    ('cnt_rescue_025', 'Rescue: Ask for a Simpler Start', 'rescue', 'intro', 'rescue', 'en', 'Could we start with the simpler version first?', 'Rescue phrase for easier entry'),
    ('cnt_rescue_026', 'Rescue: Ask for the Topic Again', 'rescue', 'intro', 'rescue', 'en', 'Could you say the topic once more before the details?', 'Rescue phrase for topic reset')
ON CONFLICT (id) DO NOTHING;
