package memory

import (
	"time"

	"memory-safe-english/services/api/internal/domain"
)

func additionalSeedCatalogMore(now time.Time) []domain.Content {
	return []domain.Content{
		{
			ID:          "cnt_self_intro_009",
			Title:       "Self Introduction: Why English Matters",
			ContentType: "reading",
			Level:       "intro",
			Topic:       "self_intro",
			Language:    "en",
			RawText:     "English matters for me because I need to explain my research to people outside my department.",
			SummaryText: "Why English matters in one clear reason",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_self_intro_010",
			Title:       "Self Introduction: Current Challenge",
			ContentType: "reading",
			Level:       "intro",
			Topic:       "self_intro",
			Language:    "en",
			RawText:     "My biggest challenge is not vocabulary. It is keeping long explanations in mind while I listen.",
			SummaryText: "Challenge statement focused on working memory",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_self_intro_011",
			Title:       "Self Introduction: Short Speaking Version",
			ContentType: "speaking_template",
			Level:       "intro",
			Topic:       "self_intro",
			Language:    "en",
			RawText:     "I am Rina. I study language learning. My focus is memory-safe communication.",
			SummaryText: "Short self introduction with three stable chunks",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_self_intro_012",
			Title:       "Self Introduction: Listening Practice",
			ContentType: "listening",
			Level:       "intro",
			Topic:       "self_intro",
			Language:    "en",
			RawText:     "Hello, I am Daichi. I work on classroom tools, and I am especially interested in clearer speaking support.",
			SummaryText: "Self introduction for short listening practice",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_daily_013",
			Title:       "Daily Reading: Return a Book",
			ContentType: "reading",
			Level:       "intro",
			Topic:       "daily",
			Language:    "en",
			RawText:     "I borrowed this book last week, but I finished it early and would like to return it today.",
			SummaryText: "Library return request with one reason",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_daily_014",
			Title:       "Daily Reading: Ask for a Receipt",
			ContentType: "reading",
			Level:       "intro",
			Topic:       "daily",
			Language:    "en",
			RawText:     "Could I have a receipt, please? I need it for my travel report.",
			SummaryText: "Receipt request with one purpose",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_daily_015",
			Title:       "Daily Listening: Platform Change",
			ContentType: "listening",
			Level:       "intro",
			Topic:       "daily",
			Language:    "en",
			RawText:     "The local train to Central Station will arrive on platform six instead of platform two.",
			SummaryText: "Transport update with one changed platform",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_daily_016",
			Title:       "Daily Listening: Store Closing",
			ContentType: "listening",
			Level:       "intro",
			Topic:       "daily",
			Language:    "en",
			RawText:     "This store will close in fifteen minutes, so please bring your final items to the front counter.",
			SummaryText: "Store closing announcement with one action",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_daily_017",
			Title:       "Daily Speaking: Ask for Simpler English",
			ContentType: "speaking_template",
			Level:       "intro",
			Topic:       "daily",
			Language:    "en",
			RawText:     "I understand a little. Could you use simpler English? The first point is enough for now.",
			SummaryText: "Short speaking template for simpler language",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_daily_018",
			Title:       "Daily Speaking: Confirm a Reservation",
			ContentType: "speaking_template",
			Level:       "intro",
			Topic:       "daily",
			Language:    "en",
			RawText:     "I have a reservation. My name is Kato. Could you check the time for me?",
			SummaryText: "Reservation confirmation in three steps",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_research_015",
			Title:       "Research Reading: Data Source",
			ContentType: "reading",
			Level:       "intermediate",
			Topic:       "research",
			Language:    "en",
			RawText:     "The dataset included classroom explanations, meeting instructions, and short academic passages with different overload profiles.",
			SummaryText: "Data source sentence with three content groups",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_research_016",
			Title:       "Research Reading: Evaluation Focus",
			ContentType: "reading",
			Level:       "intermediate",
			Topic:       "research",
			Language:    "en",
			RawText:     "We focused on whether learners could keep the main point, not whether they remembered every surface detail.",
			SummaryText: "Evaluation focus with explicit contrast",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_research_017",
			Title:       "Research Listening: Participant Comment",
			ContentType: "listening",
			Level:       "intermediate",
			Topic:       "research",
			Language:    "en",
			RawText:     "Several participants said they felt calmer because they no longer needed to hold the entire sentence at once.",
			SummaryText: "Participant feedback for listening practice",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_research_018",
			Title:       "Research Listening: Interpretation Step",
			ContentType: "listening",
			Level:       "intermediate",
			Topic:       "research",
			Language:    "en",
			RawText:     "This pattern may mean that lower pressure on short-term holding allows more attention for integration.",
			SummaryText: "Interpretation sentence with one hypothesis",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_research_019",
			Title:       "Research Speaking: Explain the Problem",
			ContentType: "speaking_template",
			Level:       "intermediate",
			Topic:       "research",
			Language:    "en",
			RawText:     "The problem is simple. Known words still collapse in long sentences. The burden is in holding and integration.",
			SummaryText: "Problem explanation in short research units",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_research_020",
			Title:       "Research Speaking: Explain the Result",
			ContentType: "speaking_template",
			Level:       "intermediate",
			Topic:       "research",
			Language:    "en",
			RawText:     "The result is clear. Shorter holding demand improved summaries. Confidence also increased.",
			SummaryText: "Result explanation in three steps",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_meeting_011",
			Title:       "Meeting Reading: Confirm the Goal",
			ContentType: "reading",
			Level:       "intermediate",
			Topic:       "meeting",
			Language:    "en",
			RawText:     "Before we discuss the design, can we agree that the main goal for today is a stable demo by Friday?",
			SummaryText: "Goal confirmation question for meetings",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_meeting_012",
			Title:       "Meeting Reading: Identify the Risk",
			ContentType: "reading",
			Level:       "intermediate",
			Topic:       "meeting",
			Language:    "en",
			RawText:     "The main risk is not the feature itself but the time needed to test edge cases before release.",
			SummaryText: "Risk statement with contrast",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_meeting_013",
			Title:       "Meeting Listening: Review Reminder",
			ContentType: "listening",
			Level:       "intermediate",
			Topic:       "meeting",
			Language:    "en",
			RawText:     "Please read the feedback summary tonight and bring one suggested change to tomorrow's check-in.",
			SummaryText: "Review reminder with one deliverable",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_meeting_014",
			Title:       "Meeting Listening: Release Condition",
			ContentType: "listening",
			Level:       "intermediate",
			Topic:       "meeting",
			Language:    "en",
			RawText:     "We can release this version only if the login issue is resolved and the onboarding text is reviewed.",
			SummaryText: "Release condition with two required items",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_meeting_015",
			Title:       "Meeting Speaking: Ask for the Main Point",
			ContentType: "speaking_template",
			Level:       "intermediate",
			Topic:       "meeting",
			Language:    "en",
			RawText:     "I want to confirm the main point. Is the priority stability first and design second?",
			SummaryText: "Meeting clarification in short units",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_meeting_016",
			Title:       "Meeting Speaking: State a Blocker",
			ContentType: "speaking_template",
			Level:       "intermediate",
			Topic:       "meeting",
			Language:    "en",
			RawText:     "I have one blocker. The login flow is unstable. I need one more day for testing.",
			SummaryText: "Blocker report in short speaking steps",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_rescue_011",
			Title:       "Rescue: Ask for the Conclusion",
			ContentType: "rescue",
			Level:       "intro",
			Topic:       "rescue",
			Language:    "en",
			RawText:     "Could you tell me the conclusion first?",
			SummaryText: "Rescue phrase for conclusion-first support",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_rescue_012",
			Title:       "Rescue: Ask for a Pause",
			ContentType: "rescue",
			Level:       "intro",
			Topic:       "rescue",
			Language:    "en",
			RawText:     "Please pause after each step.",
			SummaryText: "Rescue phrase for paced instructions",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_rescue_013",
			Title:       "Rescue: Ask What Changed",
			ContentType: "rescue",
			Level:       "intro",
			Topic:       "rescue",
			Language:    "en",
			RawText:     "What changed from the last version?",
			SummaryText: "Rescue phrase for focused comparison",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
		{
			ID:          "cnt_rescue_014",
			Title:       "Rescue: Ask to Confirm the Deadline",
			ContentType: "rescue",
			Level:       "intro",
			Topic:       "rescue",
			Language:    "en",
			RawText:     "Can we confirm the deadline once more?",
			SummaryText: "Rescue phrase for deadline confirmation",
			CreatedAt:   now,
			UpdatedAt:   now,
		},
	}
}
